#release configuration
#Wed Jan 15 09:19:10 CET 2025
completedPhase=check-poms
exec.activateProfiles=nexus
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.scm.org.springframework.samples\:spring-petclinic.developerConnection=scm\:git\:https\://github.com/JaroslawSuchGD/spring-petclinic.git
project.scm.org.springframework.samples\:spring-petclinic.tag=HEAD
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=spring-petaclinic-4.0.0
scm.tagNameFormat=@{project.version}
scm.url=scm\:git\:https\://github.com/JaroslawSuchGD/spring-petclinic.git
